### ISSUE TITLE
nan は valid な JSON の値ではない

### ISSUE THREAD

**Issue by y3eadgbe** [iwiwi/cpp-json-logger#4]
浮動小数点数を出力するときに inf や nan といった値を出力してしまう可能性があります
これらは strict な JSON では許容されません（たとえば ruby の JSON.parse は受け付けてくれません）
真面目に対処するかは微妙なところです
参考：
http://www.json.org/json-ja.html
http://d.hatena.ne.jp/m-hiyama/20080728/1217205390

**Comment by iwiwi** [comment]
ちなみに，真面目に対応するとすると，どうすればいいんだろう？
"NaN" などと出力する？

**Comment by y3eadgbe** [comment]
型が変わってしまうのが若干気持ち悪いですがそれぐらいしか無いと思います。
また、 strict なモードをつけて例外を投げるなどしてもいいかもしれません。
